# Generated by Django 4.1.4 on 2022-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutualist',
            options={'verbose_name': 'Mutualiste', 'verbose_name_plural': 'Mutualistes'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'Sms à envoyer', 'verbose_name_plural': 'Sms à envoyer'},
        ),
        migrations.AlterField(
            model_name='mutualist',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='mutualist',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='numero de telephone'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='body',
            field=models.TextField(verbose_name='corps du message'),
        ),
    ]
