# Generated by Django 4.2.5 on 2023-09-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutualist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom Prénom')),
                ('phone', models.CharField(max_length=10, verbose_name='Numéro de télephone')),
            ],
            options={
                'verbose_name': 'Mutualiste',
                'verbose_name_plural': 'Mutualistes',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
            ],
        ),
        migrations.CreateModel(
            name='SmsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepted', models.BooleanField(default=False, verbose_name='Accusé de reception')),
                ('mutualist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_service.mutualist')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_service.sms')),
            ],
        ),
        migrations.AddField(
            model_name='sms',
            name='mutualists',
            field=models.ManyToManyField(through='sms_service.SmsDetails', to='sms_service.mutualist'),
        ),
    ]
