# Generated by Django 4.2.5 on 2023-09-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutualist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom Prénom')),
                ('phone', models.CharField(max_length=10, verbose_name='Numéro de télephone')),
            ],
            options={
                'verbose_name': 'Mutualiste',
                'verbose_name_plural': 'Mutualistes',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('mutualists', models.ManyToManyField(to='sms_service.mutualist')),
            ],
            options={
                'verbose_name': 'sms à envoyer',
                'verbose_name_plural': 'sms à envoyer',
            },
        ),
    ]
